// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG3050.Data;

#nullable disable

namespace PROG3050.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231027123745_UpdateSchema")]
    partial class UpdateSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3cfce0d1-714f-4f52-ad96-16782affd069",
                            ConcurrencyStamp = "cecad61a-e785-4228-98a3-4c7394a8b930",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "c4257024-d328-4d01-b855-722f4c6ff739",
                            ConcurrencyStamp = "42b5a9d1-ad6c-4426-ac77-95e115cb3475",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "19bdd31b-193c-4bab-9574-0ec2f0cd4a5b",
                            ConcurrencyStamp = "0aa3e018-32d6-410e-a3a4-f6da13a0d561",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "aec7798a-0bf9-4171-b15b-b14745abf0a9",
                            ConcurrencyStamp = "e46e8307-4a7c-44e3-a197-9d8357189a36",
                            Name = "Member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "f79ac472-469f-4716-97fa-a8210c8806f6",
                            RoleId = "3cfce0d1-714f-4f52-ad96-16782affd069"
                        },
                        new
                        {
                            UserId = "01670fc7-3597-4daa-924d-582410dc4fbd",
                            RoleId = "c4257024-d328-4d01-b855-722f4c6ff739"
                        },
                        new
                        {
                            UserId = "c87c0f11-3f78-4c04-a8a9-42f274d1b34e",
                            RoleId = "19bdd31b-193c-4bab-9574-0ec2f0cd4a5b"
                        },
                        new
                        {
                            UserId = "a9a5b791-b1ef-4360-8c4c-cee3376d0f90",
                            RoleId = "aec7798a-0bf9-4171-b15b-b14745abf0a9"
                        },
                        new
                        {
                            UserId = "c0a0e2b5-2d05-437b-a441-9436d17b420c",
                            RoleId = "aec7798a-0bf9-4171-b15b-b14745abf0a9"
                        },
                        new
                        {
                            UserId = "bebeb3d1-24fc-4a31-83e8-90ff76a942cf",
                            RoleId = "aec7798a-0bf9-4171-b15b-b14745abf0a9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("PROG3050.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"), 1L, 1);

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "US"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EventId");

                    b.ToTable("Event");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            Description = "Welcome Newcomers! Enjoy the party!",
                            EndDateTime = new DateTime(2023, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2023, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "2023 Annual Event"
                        },
                        new
                        {
                            EventId = 2,
                            Description = "Welcome Game Developers! Enjoy the party!",
                            EndDateTime = new DateTime(2023, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDateTime = new DateTime(2023, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "2023 GameCon"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.EventUser", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventUser");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            UserId = "a9a5b791-b1ef-4360-8c4c-cee3376d0f90"
                        },
                        new
                        {
                            EventId = 2,
                            UserId = "a9a5b791-b1ef-4360-8c4c-cee3376d0f90"
                        },
                        new
                        {
                            EventId = 1,
                            UserId = "c87c0f11-3f78-4c04-a8a9-42f274d1b34e"
                        },
                        new
                        {
                            EventId = 1,
                            UserId = "01670fc7-3597-4daa-924d-582410dc4fbd"
                        },
                        new
                        {
                            EventId = 2,
                            UserId = "01670fc7-3597-4daa-924d-582410dc4fbd"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.FavouritePlatform", b =>
                {
                    b.Property<int>("FavouritePlatformId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavouritePlatformId"), 1L, 1);

                    b.Property<string>("FavouritePlatformName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FavouritePlatformId");

                    b.ToTable("FavouritePlatform");

                    b.HasData(
                        new
                        {
                            FavouritePlatformId = 1,
                            FavouritePlatformName = "PC"
                        },
                        new
                        {
                            FavouritePlatformId = 2,
                            FavouritePlatformName = "Mobile"
                        },
                        new
                        {
                            FavouritePlatformId = 3,
                            FavouritePlatformName = "Console"
                        },
                        new
                        {
                            FavouritePlatformId = 4,
                            FavouritePlatformName = "Others"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.FriendFamily", b =>
                {
                    b.Property<string>("RequesterUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceiverUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequesterUserId", "ReceiverUserId");

                    b.HasIndex("ReceiverUserId");

                    b.ToTable("FriendFamily");

                    b.HasData(
                        new
                        {
                            RequesterUserId = "01670fc7-3597-4daa-924d-582410dc4fbd",
                            ReceiverUserId = "a9a5b791-b1ef-4360-8c4c-cee3376d0f90",
                            Description = "Friend",
                            Status = "Processed"
                        },
                        new
                        {
                            RequesterUserId = "c87c0f11-3f78-4c04-a8a9-42f274d1b34e",
                            ReceiverUserId = "a9a5b791-b1ef-4360-8c4c-cee3376d0f90",
                            Description = "Family",
                            Status = "Processed"
                        },
                        new
                        {
                            RequesterUserId = "a9a5b791-b1ef-4360-8c4c-cee3376d0f90",
                            ReceiverUserId = "f79ac472-469f-4716-97fa-a8210c8806f6",
                            Description = "Friend",
                            Status = "Pending"
                        },
                        new
                        {
                            RequesterUserId = "c87c0f11-3f78-4c04-a8a9-42f274d1b34e",
                            ReceiverUserId = "f79ac472-469f-4716-97fa-a8210c8806f6",
                            Description = "Family",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameCategoryId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.HasIndex("GameCategoryId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Description = "For over two decades, Counter-Strike has offered an elite competitive experience, one shaped by millions of players from across the globe. And now the next chapter in the CS story is about to begin. This is Counter-Strike 2.",
                            GameCategoryId = 3,
                            Price = 0.0,
                            PublishDate = new DateTime(2012, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Counter-Strike 2"
                        },
                        new
                        {
                            GameId = 2,
                            Description = "Star Trek: Infinite is a grand strategy experience that lets you play your own Star Trek story as the leader of one of four major factions in the galaxy. Follow the specially crafted story or blaze your own trail in the first Star Trek grand strategy game.",
                            GameCategoryId = 1,
                            Price = 39.990000000000002,
                            PublishDate = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Trek: Infinite"
                        },
                        new
                        {
                            GameId = 3,
                            Description = "Raise a city from the ground up and transform it into a thriving metropolis with the most realistic city builder ever. Push your creativity and problem-solving to build on a scale you've never experienced. With deep simulation and a living economy, this is world-building without limits.",
                            GameCategoryId = 2,
                            Price = 59.990000000000002,
                            PublishDate = new DateTime(2023, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cities: Skylines II"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.GameCategory", b =>
                {
                    b.Property<int>("GameCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameCategoryId"), 1L, 1);

                    b.Property<string>("GameCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameCategoryId");

                    b.ToTable("GameCategory");

                    b.HasData(
                        new
                        {
                            GameCategoryId = 1,
                            GameCategoryName = "Action"
                        },
                        new
                        {
                            GameCategoryId = 2,
                            GameCategoryName = "Adventure"
                        },
                        new
                        {
                            GameCategoryId = 3,
                            GameCategoryName = "FPS"
                        },
                        new
                        {
                            GameCategoryId = 4,
                            GameCategoryName = "Shooter"
                        },
                        new
                        {
                            GameCategoryId = 5,
                            GameCategoryName = "Others"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.Gender", b =>
                {
                    b.Property<int>("GenderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenderId"), 1L, 1);

                    b.Property<string>("GenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenderId");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            GenderId = 1,
                            GenderName = "Male"
                        },
                        new
                        {
                            GenderId = 2,
                            GenderName = "Female"
                        },
                        new
                        {
                            GenderId = 3,
                            GenderName = "Others"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"), 1L, 1);

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            LanguageName = "English"
                        },
                        new
                        {
                            LanguageId = 2,
                            LanguageName = "French"
                        },
                        new
                        {
                            LanguageId = 3,
                            LanguageName = "Spanish"
                        },
                        new
                        {
                            LanguageId = 4,
                            LanguageName = "Korean"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.MailingAddress", b =>
                {
                    b.Property<int>("MailingAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MailingAddressId"), 1L, 1);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryInstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MailingAddressId");

                    b.HasIndex("ProvinceId");

                    b.ToTable("MailingAddress");

                    b.HasData(
                        new
                        {
                            MailingAddressId = 1,
                            City = "HALIFAX",
                            DeliveryInstruction = "At the door",
                            FirstName = "Tyrone",
                            LastName = "Mcgee",
                            PostalCode = "B3J 2B3",
                            ProvinceId = 7,
                            Street = "978 ARGYLE ST N"
                        },
                        new
                        {
                            MailingAddressId = 2,
                            City = "TORONTO",
                            DeliveryInstruction = "At the Post Box",
                            PostalCode = "M4K 1M8",
                            ProvinceId = 9,
                            Street = "87 DANFORTH AVE",
                            Unit = "501"
                        },
                        new
                        {
                            MailingAddressId = 3,
                            City = "BIG VALLEY",
                            PostalCode = "T0L 1K0",
                            ProvinceId = 1,
                            Street = "4 FIRST AVE S"
                        },
                        new
                        {
                            MailingAddressId = 4,
                            City = "COURTENAY",
                            DeliveryInstruction = "Ask the security Guard to get in.",
                            PostalCode = "V9N 0A7",
                            ProvinceId = 2,
                            Street = "PO BOX 4600 STN B"
                        },
                        new
                        {
                            MailingAddressId = 5,
                            ProvinceId = 1
                        },
                        new
                        {
                            MailingAddressId = 6,
                            ProvinceId = 2
                        });
                });

            modelBuilder.Entity("PROG3050.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrderId");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            OrderDate = new DateTime(2012, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddressId = 4,
                            Status = "Processed",
                            UserId = "a9a5b791-b1ef-4360-8c4c-cee3376d0f90"
                        },
                        new
                        {
                            OrderId = 2,
                            OrderDate = new DateTime(2020, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddressId = 2,
                            Status = "Processed",
                            UserId = "01670fc7-3597-4daa-924d-582410dc4fbd"
                        },
                        new
                        {
                            OrderId = 3,
                            OrderDate = new DateTime(2022, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippingAddressId = 3,
                            Status = "Pending",
                            UserId = "c87c0f11-3f78-4c04-a8a9-42f274d1b34e"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.OrderGame", b =>
                {
                    b.Property<int>("OrderGameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderGameId"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderGameId");

                    b.HasIndex("GameId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderGame");

                    b.HasData(
                        new
                        {
                            OrderGameId = 1,
                            GameId = 1,
                            OrderId = 1,
                            Quantity = 1
                        },
                        new
                        {
                            OrderGameId = 2,
                            GameId = 2,
                            OrderId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            OrderGameId = 3,
                            GameId = 2,
                            OrderId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            OrderGameId = 4,
                            GameId = 3,
                            OrderId = 2,
                            Quantity = 3
                        },
                        new
                        {
                            OrderGameId = 5,
                            GameId = 3,
                            OrderId = 3,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("PROG3050.Models.Preference", b =>
                {
                    b.Property<int>("PreferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PreferenceId"), 1L, 1);

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.HasKey("PreferenceId");

                    b.HasIndex("LanguageId");

                    b.ToTable("Preference");

                    b.HasData(
                        new
                        {
                            PreferenceId = 1,
                            LanguageId = 1
                        },
                        new
                        {
                            PreferenceId = 2,
                            LanguageId = 2
                        },
                        new
                        {
                            PreferenceId = 3,
                            LanguageId = 3
                        },
                        new
                        {
                            PreferenceId = 4,
                            LanguageId = 4
                        },
                        new
                        {
                            PreferenceId = 5,
                            LanguageId = 1
                        },
                        new
                        {
                            PreferenceId = 6,
                            LanguageId = 1
                        });
                });

            modelBuilder.Entity("PROG3050.Models.PreferenceFavouritePlatform", b =>
                {
                    b.Property<int>("PreferenceId")
                        .HasColumnType("int");

                    b.Property<int>("FavouritePlatformId")
                        .HasColumnType("int");

                    b.HasKey("PreferenceId", "FavouritePlatformId");

                    b.HasIndex("FavouritePlatformId");

                    b.ToTable("PreferenceFavouritePlatform");

                    b.HasData(
                        new
                        {
                            PreferenceId = 1,
                            FavouritePlatformId = 1
                        },
                        new
                        {
                            PreferenceId = 1,
                            FavouritePlatformId = 2
                        },
                        new
                        {
                            PreferenceId = 2,
                            FavouritePlatformId = 2
                        },
                        new
                        {
                            PreferenceId = 2,
                            FavouritePlatformId = 3
                        },
                        new
                        {
                            PreferenceId = 3,
                            FavouritePlatformId = 1
                        },
                        new
                        {
                            PreferenceId = 4,
                            FavouritePlatformId = 1
                        },
                        new
                        {
                            PreferenceId = 5,
                            FavouritePlatformId = 1
                        },
                        new
                        {
                            PreferenceId = 6,
                            FavouritePlatformId = 1
                        });
                });

            modelBuilder.Entity("PROG3050.Models.PreferenceGameCategory", b =>
                {
                    b.Property<int>("PreferenceId")
                        .HasColumnType("int");

                    b.Property<int>("GameCategoryId")
                        .HasColumnType("int");

                    b.HasKey("PreferenceId", "GameCategoryId");

                    b.HasIndex("GameCategoryId");

                    b.ToTable("PreferenceGameCategory");

                    b.HasData(
                        new
                        {
                            PreferenceId = 1,
                            GameCategoryId = 1
                        },
                        new
                        {
                            PreferenceId = 1,
                            GameCategoryId = 2
                        },
                        new
                        {
                            PreferenceId = 2,
                            GameCategoryId = 2
                        },
                        new
                        {
                            PreferenceId = 2,
                            GameCategoryId = 3
                        },
                        new
                        {
                            PreferenceId = 3,
                            GameCategoryId = 1
                        },
                        new
                        {
                            PreferenceId = 4,
                            GameCategoryId = 1
                        },
                        new
                        {
                            PreferenceId = 5,
                            GameCategoryId = 1
                        },
                        new
                        {
                            PreferenceId = 6,
                            GameCategoryId = 1
                        });
                });

            modelBuilder.Entity("PROG3050.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.ToTable("Province");

                    b.HasData(
                        new
                        {
                            ProvinceId = 1,
                            CountryId = 1,
                            ProvinceName = "AB"
                        },
                        new
                        {
                            ProvinceId = 2,
                            CountryId = 1,
                            ProvinceName = "BC"
                        },
                        new
                        {
                            ProvinceId = 3,
                            CountryId = 1,
                            ProvinceName = "MB"
                        },
                        new
                        {
                            ProvinceId = 4,
                            CountryId = 1,
                            ProvinceName = "NB"
                        },
                        new
                        {
                            ProvinceId = 5,
                            CountryId = 1,
                            ProvinceName = "NL"
                        },
                        new
                        {
                            ProvinceId = 6,
                            CountryId = 1,
                            ProvinceName = "NT"
                        },
                        new
                        {
                            ProvinceId = 7,
                            CountryId = 1,
                            ProvinceName = "NS"
                        },
                        new
                        {
                            ProvinceId = 8,
                            CountryId = 1,
                            ProvinceName = "NU"
                        },
                        new
                        {
                            ProvinceId = 9,
                            CountryId = 1,
                            ProvinceName = "ON"
                        },
                        new
                        {
                            ProvinceId = 10,
                            CountryId = 1,
                            ProvinceName = "PE"
                        },
                        new
                        {
                            ProvinceId = 11,
                            CountryId = 1,
                            ProvinceName = "QC"
                        },
                        new
                        {
                            ProvinceId = 12,
                            CountryId = 1,
                            ProvinceName = "SK"
                        },
                        new
                        {
                            ProvinceId = 13,
                            CountryId = 1,
                            ProvinceName = "YT"
                        },
                        new
                        {
                            ProvinceId = 14,
                            CountryId = 2,
                            ProvinceName = "AL"
                        },
                        new
                        {
                            ProvinceId = 15,
                            CountryId = 2,
                            ProvinceName = "AK"
                        },
                        new
                        {
                            ProvinceId = 16,
                            CountryId = 2,
                            ProvinceName = "AZ"
                        },
                        new
                        {
                            ProvinceId = 17,
                            CountryId = 2,
                            ProvinceName = "AR"
                        },
                        new
                        {
                            ProvinceId = 18,
                            CountryId = 2,
                            ProvinceName = "CA"
                        },
                        new
                        {
                            ProvinceId = 19,
                            CountryId = 2,
                            ProvinceName = "CO"
                        },
                        new
                        {
                            ProvinceId = 20,
                            CountryId = 2,
                            ProvinceName = "CT"
                        },
                        new
                        {
                            ProvinceId = 21,
                            CountryId = 2,
                            ProvinceName = "DE"
                        },
                        new
                        {
                            ProvinceId = 22,
                            CountryId = 2,
                            ProvinceName = "DC"
                        },
                        new
                        {
                            ProvinceId = 23,
                            CountryId = 2,
                            ProvinceName = "FL"
                        },
                        new
                        {
                            ProvinceId = 24,
                            CountryId = 2,
                            ProvinceName = "GA"
                        },
                        new
                        {
                            ProvinceId = 25,
                            CountryId = 2,
                            ProvinceName = "HI"
                        },
                        new
                        {
                            ProvinceId = 26,
                            CountryId = 2,
                            ProvinceName = "ID"
                        },
                        new
                        {
                            ProvinceId = 27,
                            CountryId = 2,
                            ProvinceName = "IL"
                        },
                        new
                        {
                            ProvinceId = 28,
                            CountryId = 2,
                            ProvinceName = "IN"
                        },
                        new
                        {
                            ProvinceId = 29,
                            CountryId = 2,
                            ProvinceName = "IA"
                        },
                        new
                        {
                            ProvinceId = 30,
                            CountryId = 2,
                            ProvinceName = "KS"
                        },
                        new
                        {
                            ProvinceId = 31,
                            CountryId = 2,
                            ProvinceName = "KY"
                        },
                        new
                        {
                            ProvinceId = 32,
                            CountryId = 2,
                            ProvinceName = "LA"
                        },
                        new
                        {
                            ProvinceId = 33,
                            CountryId = 2,
                            ProvinceName = "ME"
                        },
                        new
                        {
                            ProvinceId = 34,
                            CountryId = 2,
                            ProvinceName = "MD"
                        },
                        new
                        {
                            ProvinceId = 35,
                            CountryId = 2,
                            ProvinceName = "MA"
                        },
                        new
                        {
                            ProvinceId = 37,
                            CountryId = 2,
                            ProvinceName = "MI"
                        },
                        new
                        {
                            ProvinceId = 38,
                            CountryId = 2,
                            ProvinceName = "MN"
                        },
                        new
                        {
                            ProvinceId = 39,
                            CountryId = 2,
                            ProvinceName = "MS"
                        },
                        new
                        {
                            ProvinceId = 40,
                            CountryId = 2,
                            ProvinceName = "MO"
                        },
                        new
                        {
                            ProvinceId = 41,
                            CountryId = 2,
                            ProvinceName = "MT"
                        },
                        new
                        {
                            ProvinceId = 42,
                            CountryId = 2,
                            ProvinceName = "NE"
                        },
                        new
                        {
                            ProvinceId = 43,
                            CountryId = 2,
                            ProvinceName = "NV"
                        },
                        new
                        {
                            ProvinceId = 44,
                            CountryId = 2,
                            ProvinceName = "NH"
                        },
                        new
                        {
                            ProvinceId = 45,
                            CountryId = 2,
                            ProvinceName = "NJ"
                        },
                        new
                        {
                            ProvinceId = 46,
                            CountryId = 2,
                            ProvinceName = "NM"
                        },
                        new
                        {
                            ProvinceId = 47,
                            CountryId = 2,
                            ProvinceName = "NY"
                        },
                        new
                        {
                            ProvinceId = 48,
                            CountryId = 2,
                            ProvinceName = "NC"
                        },
                        new
                        {
                            ProvinceId = 49,
                            CountryId = 2,
                            ProvinceName = "NY"
                        },
                        new
                        {
                            ProvinceId = 50,
                            CountryId = 2,
                            ProvinceName = "NC"
                        },
                        new
                        {
                            ProvinceId = 51,
                            CountryId = 2,
                            ProvinceName = "ND"
                        },
                        new
                        {
                            ProvinceId = 52,
                            CountryId = 2,
                            ProvinceName = "OH"
                        },
                        new
                        {
                            ProvinceId = 53,
                            CountryId = 2,
                            ProvinceName = "OK"
                        },
                        new
                        {
                            ProvinceId = 54,
                            CountryId = 2,
                            ProvinceName = "OR"
                        },
                        new
                        {
                            ProvinceId = 55,
                            CountryId = 2,
                            ProvinceName = "PA"
                        },
                        new
                        {
                            ProvinceId = 56,
                            CountryId = 2,
                            ProvinceName = "RI"
                        },
                        new
                        {
                            ProvinceId = 57,
                            CountryId = 2,
                            ProvinceName = "SC"
                        },
                        new
                        {
                            ProvinceId = 58,
                            CountryId = 2,
                            ProvinceName = "SD"
                        },
                        new
                        {
                            ProvinceId = 59,
                            CountryId = 2,
                            ProvinceName = "TN"
                        },
                        new
                        {
                            ProvinceId = 60,
                            CountryId = 2,
                            ProvinceName = "TX"
                        },
                        new
                        {
                            ProvinceId = 61,
                            CountryId = 2,
                            ProvinceName = "UT"
                        },
                        new
                        {
                            ProvinceId = 62,
                            CountryId = 2,
                            ProvinceName = "VT"
                        },
                        new
                        {
                            ProvinceId = 63,
                            CountryId = 2,
                            ProvinceName = "VA"
                        },
                        new
                        {
                            ProvinceId = 64,
                            CountryId = 2,
                            ProvinceName = "WA"
                        },
                        new
                        {
                            ProvinceId = 65,
                            CountryId = 2,
                            ProvinceName = "WV"
                        },
                        new
                        {
                            ProvinceId = 66,
                            CountryId = 2,
                            ProvinceName = "WI"
                        },
                        new
                        {
                            ProvinceId = 67,
                            CountryId = 2,
                            ProvinceName = "WY"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"), 1L, 1);

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("PROG3050.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ReviewId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Description = "Counter-Strike 2 is the best game that I've ever played. Actions and graphics are amazing.",
                            GameId = 1,
                            Rating = 5.0,
                            Status = "Pending",
                            Title = "The Best Game!",
                            UserId = "a9a5b791-b1ef-4360-8c4c-cee3376d0f90"
                        },
                        new
                        {
                            ReviewId = 2,
                            Description = "Star Trek: Infinite is a decent game to play. I'll definitely recommend you to play.",
                            GameId = 2,
                            Rating = 4.0,
                            Status = "Processed",
                            Title = "Good Game",
                            UserId = "01670fc7-3597-4daa-924d-582410dc4fbd"
                        },
                        new
                        {
                            ReviewId = 3,
                            Description = "Counter-Strike 2 is the best game that I've ever played. Actions and graphics are amazing.",
                            GameId = 3,
                            Rating = 2.0,
                            Status = "Pending",
                            Title = "Bad Game!",
                            UserId = "c87c0f11-3f78-4c04-a8a9-42f274d1b34e"
                        },
                        new
                        {
                            ReviewId = 4,
                            Description = "Counter-Strike 2 is the best game that I've ever played. Actions and graphics are amazing.",
                            GameId = 2,
                            Rating = 2.0,
                            Status = "Pending",
                            Title = "Bad Game!",
                            UserId = "c87c0f11-3f78-4c04-a8a9-42f274d1b34e"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.ShippingAddress", b =>
                {
                    b.Property<int>("ShippingAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShippingAddressId"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryInstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShippingAddressId");

                    b.ToTable("ShippingAddress");

                    b.HasData(
                        new
                        {
                            ShippingAddressId = 1,
                            City = "HALIFAX",
                            Country = "Canada",
                            DeliveryInstruction = "At the door",
                            PostalCode = "B3J 2B3",
                            Province = "NU",
                            Street = "978 ARGYLE ST N"
                        },
                        new
                        {
                            ShippingAddressId = 2,
                            City = "TORONTO",
                            Country = "Canada",
                            DeliveryInstruction = "At the Post Box",
                            PostalCode = "M4K 1M8",
                            Province = "ON",
                            Street = "87 DANFORTH AVE",
                            Unit = "501"
                        },
                        new
                        {
                            ShippingAddressId = 3,
                            City = "BIG VALLEY",
                            Country = "Canada",
                            PostalCode = "T0L 1K0",
                            Province = "AB",
                            Street = "4 FIRST AVE S"
                        },
                        new
                        {
                            ShippingAddressId = 4,
                            City = "COURTENAY",
                            Country = "Canada",
                            DeliveryInstruction = "Ask the security Guard to get in.",
                            PostalCode = "V9N 0A7",
                            Province = "BC",
                            Street = "PO BOX 4600 STN B"
                        });
                });

            modelBuilder.Entity("PROG3050.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAddressSame")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPromotionalEmail")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MailingAddressId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("PreferenceId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("GenderId");

                    b.HasIndex("MailingAddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PreferenceId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f79ac472-469f-4716-97fa-a8210c8806f6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4ec00049-0f59-448c-ae0f-74dd1d0c5f85",
                            Email = "superadmin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Tyrone",
                            GenderId = 3,
                            IsAddressSame = false,
                            IsPromotionalEmail = false,
                            LastName = "Mcgee",
                            LockoutEnabled = false,
                            MailingAddressId = 1,
                            NormalizedEmail = "SUPERADMIN@GMAIL.COM",
                            NormalizedUserName = "SUPERADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEBPXiQnRhhipu6JNNC1HnAziHzma5pvlTmkyqw9cNWOjuDN7pOlnZ8iYoK1mWU49Eg==",
                            PhoneNumberConfirmed = true,
                            PreferenceId = 1,
                            SecurityStamp = "ec788bc9-d562-45e0-bd01-1e4aa7e3968b",
                            TwoFactorEnabled = false,
                            UserName = "SuperAdmin"
                        },
                        new
                        {
                            Id = "01670fc7-3597-4daa-924d-582410dc4fbd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "977d7c93-d318-4a27-9ada-0c2b5ea29b4e",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "William",
                            GenderId = 3,
                            IsAddressSame = false,
                            IsPromotionalEmail = false,
                            LastName = "Potter",
                            LockoutEnabled = false,
                            MailingAddressId = 2,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEEXi1JRo8c9ROU2JSNNWRutYFrUjA7pH/xl8VJDWwiHy7fcA5Efe2DwwLIwzc5IBhw==",
                            PhoneNumberConfirmed = true,
                            PreferenceId = 2,
                            SecurityStamp = "748b72fa-389e-4f8f-9d69-fec63e3c38f3",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "c87c0f11-3f78-4c04-a8a9-42f274d1b34e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6bd128f8-1ab5-4da9-abc7-9272fdaafaa4",
                            Email = "moderator@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Francis",
                            GenderId = 3,
                            IsAddressSame = false,
                            IsPromotionalEmail = false,
                            LastName = "Ramos",
                            LockoutEnabled = false,
                            MailingAddressId = 3,
                            NormalizedEmail = "MODERATOR@GMAIL.COM",
                            NormalizedUserName = "MODERATOR",
                            PasswordHash = "AQAAAAEAACcQAAAAEDi0+2C7ZO+q2236wnpSl5T+2KOFH4ynll4KiW2oUjEitgywrsuKzlJo4VhUkEUprQ==",
                            PhoneNumberConfirmed = true,
                            PreferenceId = 3,
                            SecurityStamp = "27c0d74d-01ab-4f8f-bf16-8ca21560cec1",
                            TwoFactorEnabled = false,
                            UserName = "Moderator"
                        },
                        new
                        {
                            Id = "a9a5b791-b1ef-4360-8c4c-cee3376d0f90",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fb117f7d-17ad-4b9e-a571-ec73afff73d5",
                            Email = "member@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Ernest",
                            GenderId = 3,
                            IsAddressSame = false,
                            IsPromotionalEmail = false,
                            LastName = "Mcknight",
                            LockoutEnabled = false,
                            MailingAddressId = 4,
                            NormalizedEmail = "MEMBER@GMAIL.COM",
                            NormalizedUserName = "MEMBER",
                            PasswordHash = "AQAAAAEAACcQAAAAEBNJVwkkrHNd1h/0JYhIiVNO1xUtImOiM3pWYkQumVt4aicZxNWJnvSlU+lmJ5MjXw==",
                            PhoneNumberConfirmed = true,
                            PreferenceId = 4,
                            SecurityStamp = "a5f7d72d-8a94-4575-a66d-c1199a42bb3e",
                            TwoFactorEnabled = false,
                            UserName = "Member"
                        },
                        new
                        {
                            Id = "c0a0e2b5-2d05-437b-a441-9436d17b420c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2bfafa23-dbe8-49e9-9e1c-dc8efc7e270d",
                            Email = "tester1@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Test1FirstName",
                            GenderId = 3,
                            IsAddressSame = false,
                            IsPromotionalEmail = false,
                            LastName = "Test1LastName",
                            LockoutEnabled = false,
                            MailingAddressId = 5,
                            NormalizedEmail = "TESTER1@GMAIL.COM",
                            NormalizedUserName = "TESTER1",
                            PasswordHash = "AQAAAAEAACcQAAAAED3HgKO6DbQCU64Sj8mgPpYR8CmHIkBm/GvteKj1LhegYxHt01dM6Uor8haTmzbsmQ==",
                            PhoneNumberConfirmed = true,
                            PreferenceId = 5,
                            SecurityStamp = "f9a69396-28b4-4560-b657-062f70202669",
                            TwoFactorEnabled = false,
                            UserName = "Tester1"
                        },
                        new
                        {
                            Id = "bebeb3d1-24fc-4a31-83e8-90ff76a942cf",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb9bfac6-68f9-464c-97e2-c9c2ef639ffe",
                            Email = "tester2@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Test2FirstName",
                            GenderId = 3,
                            IsAddressSame = false,
                            IsPromotionalEmail = false,
                            LastName = "Test2LastName",
                            LockoutEnabled = false,
                            MailingAddressId = 6,
                            NormalizedEmail = "TESTER2@GMAIL.COM",
                            NormalizedUserName = "TESTER2",
                            PasswordHash = "AQAAAAEAACcQAAAAEERw5yRlPQ09jt0WiZ2qGgpBHrZUvjxeO2DLMykt+yQo1mtv/Nx06CKJqmh5mfhGCA==",
                            PhoneNumberConfirmed = true,
                            PreferenceId = 6,
                            SecurityStamp = "792c423f-ca9e-49df-b0f5-7a6ff3352553",
                            TwoFactorEnabled = false,
                            UserName = "Tester2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("PROG3050.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("PROG3050.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG3050.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("PROG3050.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PROG3050.Models.EventUser", b =>
                {
                    b.HasOne("PROG3050.Models.Event", "Event")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG3050.Models.User", "User")
                        .WithMany("EventUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PROG3050.Models.FriendFamily", b =>
                {
                    b.HasOne("PROG3050.Models.User", "ReceiverUser")
                        .WithMany("FriendFamilyReceiver")
                        .HasForeignKey("ReceiverUserId")
                        .IsRequired();

                    b.HasOne("PROG3050.Models.User", "RequesterUser")
                        .WithMany("FriendFamilyRequester")
                        .HasForeignKey("RequesterUserId")
                        .IsRequired();

                    b.Navigation("ReceiverUser");

                    b.Navigation("RequesterUser");
                });

            modelBuilder.Entity("PROG3050.Models.Game", b =>
                {
                    b.HasOne("PROG3050.Models.GameCategory", "GameCategory")
                        .WithMany()
                        .HasForeignKey("GameCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameCategory");
                });

            modelBuilder.Entity("PROG3050.Models.MailingAddress", b =>
                {
                    b.HasOne("PROG3050.Models.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("PROG3050.Models.Order", b =>
                {
                    b.HasOne("PROG3050.Models.ShippingAddress", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG3050.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PROG3050.Models.OrderGame", b =>
                {
                    b.HasOne("PROG3050.Models.Game", "Game")
                        .WithMany("OrderGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG3050.Models.Order", "Order")
                        .WithMany("OrderGames")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PROG3050.Models.Preference", b =>
                {
                    b.HasOne("PROG3050.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("PROG3050.Models.PreferenceFavouritePlatform", b =>
                {
                    b.HasOne("PROG3050.Models.FavouritePlatform", "FavouritePlatform")
                        .WithMany("PreferenceFavouritePlatforms")
                        .HasForeignKey("FavouritePlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG3050.Models.Preference", "Preference")
                        .WithMany("PreferenceFavouritePlatforms")
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FavouritePlatform");

                    b.Navigation("Preference");
                });

            modelBuilder.Entity("PROG3050.Models.PreferenceGameCategory", b =>
                {
                    b.HasOne("PROG3050.Models.GameCategory", "GameCategory")
                        .WithMany("PreferenceGameCategories")
                        .HasForeignKey("GameCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG3050.Models.Preference", "Preference")
                        .WithMany("PreferenceGameCategories")
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameCategory");

                    b.Navigation("Preference");
                });

            modelBuilder.Entity("PROG3050.Models.Province", b =>
                {
                    b.HasOne("PROG3050.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("PROG3050.Models.Review", b =>
                {
                    b.HasOne("PROG3050.Models.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG3050.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PROG3050.Models.User", b =>
                {
                    b.HasOne("PROG3050.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG3050.Models.MailingAddress", "MailingAddress")
                        .WithMany()
                        .HasForeignKey("MailingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG3050.Models.Preference", "Preference")
                        .WithMany()
                        .HasForeignKey("PreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gender");

                    b.Navigation("MailingAddress");

                    b.Navigation("Preference");
                });

            modelBuilder.Entity("PROG3050.Models.Event", b =>
                {
                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("PROG3050.Models.FavouritePlatform", b =>
                {
                    b.Navigation("PreferenceFavouritePlatforms");
                });

            modelBuilder.Entity("PROG3050.Models.Game", b =>
                {
                    b.Navigation("OrderGames");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("PROG3050.Models.GameCategory", b =>
                {
                    b.Navigation("PreferenceGameCategories");
                });

            modelBuilder.Entity("PROG3050.Models.Order", b =>
                {
                    b.Navigation("OrderGames");
                });

            modelBuilder.Entity("PROG3050.Models.Preference", b =>
                {
                    b.Navigation("PreferenceFavouritePlatforms");

                    b.Navigation("PreferenceGameCategories");
                });

            modelBuilder.Entity("PROG3050.Models.User", b =>
                {
                    b.Navigation("EventUsers");

                    b.Navigation("FriendFamilyReceiver");

                    b.Navigation("FriendFamilyRequester");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
